#page title
page_title                                :  ارسال                             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 556                              # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : ارسال                                          # Enter Google Play Store URL.
presskit_download_link                    : https://ersalye.github.io.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : /assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : ارسال                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : لخدمات النفل الداخلي والخارجي                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : مع ارسال طلبك بين يديدك .

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : ارسال                                
your_link                                 : https://ersalye.github.io.com                     
your_city                                 : Yemen                                
email_address                             : eng.dev.ezz@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : تنوع في الخدمات
    description                           : يضم ارسال الكثير من الخدمات ويمكن اضافة اي خدمة جديدة 
    fontawesome_icon_name                 : magic
    
  - title                                 : التصميم
    description                           : تم تصميم التطبيقات بتصميم رائع وسهل الاستخدام مع امكانية اغلاق التطبيق بكلمة سر وخدمات اخرى.
    fontawesome_icon_name                 : mobile

  - title                                 : توصيل سريع وامن
    description                           : نهتم بتوصيل كافة طلباتك باقصى سرعة واامن طريقة لاي مكان
    fontawesome_icon_name                 : play-circle

  - title                                 : تحديث مستمر وفوري
    description                           : تتم تحديث بيانات التطبيق بشكل مباشر وسريع مع وصول اشعارات واتنبيهات للتطبيق .
    fontawesome_icon_name                 : sync

  - title                                 : تطبيقات مختلفة
    description                           : يوجد تطبيق لكل نوع مستخدم من مقدم خدمة وعميل ومندوب توصيل
    fontawesome_icon_name                 : adjust
  
  - title                                 : تميز الان مع ارسال
    description                           : يمكن لاي مقدم خدمة واي محل بكافة انواعها ان يصبح من خدمات ارسال
    fontawesome_icon_name                 : star

  - title                                 : Offline
    description                           : يمكنك تصفح التطبيق دون الحاجة الى انترنت بعد اول مرة فتح وتحميل للبيانات.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : دعم فني
    description                           : يمكنك التواصل مع الدعم الفني وادارة النظام عبر دردشة مباشرة داخل التطبيق او عبر وسائل اخرى
    fontawesome_icon_name                 : envelope

  - title                                 : انظم الى فريق ارسال
    description                           : يمكنك ان تصبج مندوب توصيل لارسال ولايتطلب منك الا توفير وسيلة توصيل مثل دراجة نارية او هوائية او غيرها
    fontawesome_icon_name                 : truck

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : blue                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF4141"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FF4141"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
